/*
 * GENERATED BY GEMINI
 *
 *
 */

import org.junit.jupiter.api.*;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class APITest {

    private static API api;
    private static final String DB_FILE_PATH = "system.odb";

    // ANSI Colors for Console Output
    private static final String ANSI_RED = "\u001B[31m";
    private static final String ANSI_GREEN = "\u001B[32m";
    private static final String ANSI_RESET = "\u001B[0m";

    // List to store failed test details for summary output
    private static final List<String> failedLog = new ArrayList<>();

    @BeforeAll
    public static void setUpDatabase() {
        if (api != null) {
            api.close();
        }

        // Delete existing ObjectDB database files to start completely fresh
        File dbFile = new File(DB_FILE_PATH);
        if (dbFile.exists()) {
            dbFile.delete();
        }
        File dbLogFile = new File(DB_FILE_PATH + "$");
        if (dbLogFile.exists()) {
            dbLogFile.delete();
        }

        api = API.getInstance();
    }

    @AfterAll
    public static void printSummaryAndTearDown() {
        if (api != null) {
            api.close();
        }

        // --- PRINT FAILED CASES SUMMARY IN RED TEXT ---
        System.out.println("\n==================================================");
        System.out.println("              TEST SUITE SUMMARY                  ");
        System.out.println("==================================================");

        if (failedLog.isEmpty()) {
            System.out.println(ANSI_GREEN + "✔ ALL TESTS PASSED SUCCESSFULLY!" + ANSI_RESET);
        } else {
            System.out.println(ANSI_RED + "❌ FAILED CASES DETECTED (" + failedLog.size() + "):" + ANSI_RESET);
            System.out.println("--------------------------------------------------");
            for (String failure : failedLog) {
                // Output every failure message in Red
                System.out.println(ANSI_RED + failure + ANSI_RESET);
            }
        }
        System.out.println("==================================================\n");
    }

    /**
     * Custom assertion runner to capture failures in our red log list
     */
    private void runTest(String testName, Runnable testLogic) {
        try {
            testLogic.run();
        } catch (Throwable t) {
            failedLog.add("[" + testName + "] Reason: " + t.getMessage());
            throw t; // Re-throw to let JUnit register the failure
        }
    }

    // ==========================================
    // 1. POPULATION & SEEDING TESTS
    // ==========================================

    @Test
    @Order(1)
    @DisplayName("Test 1: Populate Database with initial seed data")
    public void testPopulate() {
        runTest("Test 1: Populate Database", () -> {
            assertDoesNotThrow(() -> api.populate());

            String researchers = api.getAllResearcherOutput();
            assertFalse(researchers.contains("No researchers found"), "Researchers should exist after populate()");

            String equipment = api.getAllEquipmentOutput();
            assertFalse(equipment.contains("No Equipment found"), "Equipment should exist after populate()");

            String bookings = api.getAllBookings();
            assertFalse(bookings.contains("No bookings found"), "Bookings should exist after populate()");
        });
    }

    // ==========================================
    // 2. REGISTRATION TESTS
    // ==========================================

    @Test
    @Order(2)
    @DisplayName("Test 2: Register New Researcher")
    public void testRegisterResearcher() {
        runTest("Test 2: Register Researcher", () -> {
            boolean success = api.registerResearcher("Jane Doe", "Computer Science", "jane.doe@up.ac.za");
            assertTrue(success, "Registering a new researcher should return true");

            String allResearchers = api.getAllResearcherOutput();
            assertTrue(allResearchers.contains("Jane Doe"), "New researcher should appear in researcher list");
        });
    }

    @Test
    @Order(3)
    @DisplayName("Test 3: Register New Equipment")
    public void testRegisterEquipment() {
        runTest("Test 3: Register Equipment", () -> {
            boolean success = api.registerEquipment("Quantum Spectrometer", "Physics", "01/01/2026", 150000.0, "Available");
            assertTrue(success, "Registering equipment should return true");

            String availableEq = api.getAvailableEquipment();
            assertTrue(availableEq.contains("Quantum Spectrometer"), "Newly registered equipment should be available");
        });
    }

    // ==========================================
    // 3. BOOKING CREATION & BUSINESS RULE TESTS
    // ==========================================

    @Test
    @Order(4)
    @DisplayName("Test 4: Create Valid Booking")
    public void testCreateValidBooking() {
        runTest("Test 4: Create Valid Booking", () -> {
            String result = api.createBooking("28/08/2026", "10:00", "12:00", "Spectral Analysis", 1L, 1L);
            assertEquals("Success", result, "Valid booking creation should return 'Success'");
        });
    }

    @Test
    @Order(5)
    @DisplayName("Test 5: Rule Check - Out of Service Equipment cannot be booked")
    public void testCreateBookingOutOfServiceEquipment() {
        runTest("Test 5: Out of Service Equipment Rule", () -> {
            String result = api.createBooking("29/08/2026", "10:00", "12:00", "Faulty Test", 1L, 5L);
            assertEquals("Equipment does not exist, or is unavailable (or missing ID input)", result);
        });
    }

    @Test
    @Order(6)
    @DisplayName("Test 6: Rule Check - Duplicate booking on same equipment same day")
    public void testCreateDuplicateEquipmentBookingSameDay() {
        runTest("Test 6: Duplicate Equipment Same Day Rule", () -> {
            api.createBooking("30/08/2026", "08:00", "10:00", "Initial Run", 2L, 2L);
            String result = api.createBooking("30/08/2026", "13:00", "15:00", "Secondary Run", 2L, 2L);
            assertEquals("Equipment has already been booked today", result);
        });
    }

@Test
@Order(7)
@DisplayName("Test 7: Rule Check - Buffer/Overlap collision (< 10 mins apart)")
public void testCreateBookingTimeOverlap() {
    runTest("Test 7: 10-Min Buffer / Overlap Rule", () -> {
        // First booking on Equipment #3: 10:00 - 12:00
        api.createBooking("31/08/2026", "10:00", "12:00", "Slot 1", 1L, 3L);

        // Second booking: 12:05 - 14:00 (Only 5 min gap -> Violates 10-min buffer)
        String result = api.createBooking("31/08/2026", "12:05", "14:00", "Slot 2", 2L, 3L);

        // Updated assertion: checks that the return string CONTAINS your message prefix
        assertTrue(result.contains("Time overlap in bookings"), 
                "Expected overlap message, but got: " + result);
    });
}
    // ==========================================
    // 4. SEARCH & SUMMARY TESTS
    // ==========================================

    @Test
    @Order(8)
    @DisplayName("Test 8: Search Researcher by ID")
    public void testSearchResearcher() {
        runTest("Test 8: Search Researcher", () -> {
            String result = api.searchResearcher(1L);
            assertFalse(result.contains("No researchers found"), "Should find researcher with rID = 1");
            assertTrue(result.contains("Researcher: 1"), "Result string should contain researcher details");
        });
    }
@Test
@Order(9)
@DisplayName("Test 9: Equipment Summary Total Cost")
public void testGetEquipmentSummary() {
    runTest("Test 9: Equipment Summary Cost", () -> {
        String summary = api.getEquipmentSummary();
        assertNotNull(summary, "Equipment summary should not be null");
        assertTrue(summary.contains("Equipment Summary:") || summary.contains("Total"), 
                "Summary should contain header details");
    });
}

    // ==========================================
    // 5. UNIMPLEMENTED FUNCTIONALITY STUBS
    // ==========================================

    @Test
    @Order(10)
    @DisplayName("Test 10: Verify missing methods implementation")
    public void testUnimplementedMethods() {
        runTest("Test 10: Unimplemented Stubs Check", () -> {
            assertNotEquals("None", api.getResearcherBookings(1L), "getResearcherBookings() needs implementation");
            assertNotEquals("None", api.getUnusedEquipment(), "getUnusedEquipment() needs implementation");
            assertNotEquals("None", api.getHighestBookingResearchers(), "getHighestBookingResearchers() needs implementation");
            assertTrue(api.updateBooking(1L), "updateBooking() needs implementation");
            assertTrue(api.cancelBooking(1L), "cancelBooking() needs implementation");
        });
    }
}
